[package]
name = "chaum_pedersen_zkp"
version = "0.1.0"
edition = "2021"

[lib]
name = "chaum_pedersen_zkp"
crate-type = ["lib"]

[dependencies]
num-bigint = { version = "0.4.4", features = ["rand"] }
num-traits = "0.2.18"
rand = "0.8.5"
